kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: gamification-fe-services-staging
  namespace: {{ .Values.name.space }}
  labels:
    app.kubernetes.io/managed-by: Helm
    run: gamification-fe-staging
spec:
  host: gamification-staging.apps.mypaas.telkom.co.id
  to:
    kind: Service
    name: gamification-fe-services-staging
    weight: 100
  port:
    targetPort: 3000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
status:
  ingress:
    - host: gamification-staging.apps.mypaas.telkom.co.id
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
      wildcardPolicy: None
      routerCanonicalHostname: router-default.apps.mypaas.telkom.co.id