apiVersion: v1
kind: Service
metadata:
  name: gamification-fe-services-staging
  labels:
    run: gamification-fe-staging
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: gamification-fe-staging