apiVersion: v1
kind: Service
metadata:
  name: gamification-fe-services-production
  labels:
    run: gamification-frontend-production
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: gamification-frontend-production