# k8s deployment menggunakan Helm --> see /.k8s-deploy.old.yml untuk versi non Helm (pada dasarnya sama)
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: gamification-fe-services-dev
    meta.helm.sh/release-namespace: {{ .Values.name.space }}
  labels:
    app: gamification-frontend-dev
    app.kubernetes.io/managed-by: Helm
  name: gamification-frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamification-frontend-dev
  template:
    metadata:
      labels:
        app: gamification-frontend-dev
    spec:
      containers:
      - image: harbor.telkom.co.id/dit-bpd-gamification/gamification-fe:{{ .Values.image.version }}
        name: gamification-frontend-dev
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: nextenv
      imagePullSecrets:
      - name: {{ .Values.secret.name }}
