apiVersion: v1
kind: Service
metadata:
  name: gamification-fe-services-dev
  labels:
    run: gamification-frontend-dev
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: gamification-frontend-dev